/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelatorioContasRouteImport } from './routes/relatorio-contas'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as OrdensCompraRouteImport } from './routes/ordens-compra'
import { Route as OrdensRouteImport } from './routes/ordens'
import { Route as NotasCompraRouteImport } from './routes/notas-compra'
import { Route as LogisticaRouteImport } from './routes/logistica'
import { Route as ImportacaoRouteImport } from './routes/importacao'
import { Route as FuncionariosRouteImport } from './routes/funcionarios'
import { Route as FornecedoresRouteImport } from './routes/fornecedores'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as ContasRouteImport } from './routes/contas'
import { Route as ComprasRouteImport } from './routes/compras'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendasIndexRouteImport } from './routes/vendas.index'
import { Route as VendasNovoRouteImport } from './routes/vendas.novo'
import { Route as VendasIdRouteImport } from './routes/vendas.$id'
import { Route as ObrasIdRouteImport } from './routes/obras.$id'
import { Route as EstoqueEntradasRouteImport } from './routes/estoque.entradas'

const RelatorioContasRoute = RelatorioContasRouteImport.update({
  id: '/relatorio-contas',
  path: '/relatorio-contas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdensCompraRoute = OrdensCompraRouteImport.update({
  id: '/ordens-compra',
  path: '/ordens-compra',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdensRoute = OrdensRouteImport.update({
  id: '/ordens',
  path: '/ordens',
  getParentRoute: () => rootRouteImport,
} as any)
const NotasCompraRoute = NotasCompraRouteImport.update({
  id: '/notas-compra',
  path: '/notas-compra',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticaRoute = LogisticaRouteImport.update({
  id: '/logistica',
  path: '/logistica',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportacaoRoute = ImportacaoRouteImport.update({
  id: '/importacao',
  path: '/importacao',
  getParentRoute: () => rootRouteImport,
} as any)
const FuncionariosRoute = FuncionariosRouteImport.update({
  id: '/funcionarios',
  path: '/funcionarios',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedoresRoute = FornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const ContasRoute = ContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasRoute = ComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasIndexRoute = VendasIndexRouteImport.update({
  id: '/vendas/',
  path: '/vendas/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasNovoRoute = VendasNovoRouteImport.update({
  id: '/vendas/novo',
  path: '/vendas/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasIdRoute = VendasIdRouteImport.update({
  id: '/vendas/$id',
  path: '/vendas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrasIdRoute = ObrasIdRouteImport.update({
  id: '/obras/$id',
  path: '/obras/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueEntradasRoute = EstoqueEntradasRouteImport.update({
  id: '/estoque/entradas',
  path: '/estoque/entradas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof ClientesRoute
  '/compras': typeof ComprasRoute
  '/contas': typeof ContasRoute
  '/financeiro': typeof FinanceiroRoute
  '/fornecedores': typeof FornecedoresRoute
  '/funcionarios': typeof FuncionariosRoute
  '/importacao': typeof ImportacaoRoute
  '/logistica': typeof LogisticaRoute
  '/notas-compra': typeof NotasCompraRoute
  '/ordens': typeof OrdensRoute
  '/ordens-compra': typeof OrdensCompraRoute
  '/produtos': typeof ProdutosRoute
  '/relatorio-contas': typeof RelatorioContasRoute
  '/estoque/entradas': typeof EstoqueEntradasRoute
  '/obras/$id': typeof ObrasIdRoute
  '/vendas/$id': typeof VendasIdRoute
  '/vendas/novo': typeof VendasNovoRoute
  '/vendas/': typeof VendasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof ClientesRoute
  '/compras': typeof ComprasRoute
  '/contas': typeof ContasRoute
  '/financeiro': typeof FinanceiroRoute
  '/fornecedores': typeof FornecedoresRoute
  '/funcionarios': typeof FuncionariosRoute
  '/importacao': typeof ImportacaoRoute
  '/logistica': typeof LogisticaRoute
  '/notas-compra': typeof NotasCompraRoute
  '/ordens': typeof OrdensRoute
  '/ordens-compra': typeof OrdensCompraRoute
  '/produtos': typeof ProdutosRoute
  '/relatorio-contas': typeof RelatorioContasRoute
  '/estoque/entradas': typeof EstoqueEntradasRoute
  '/obras/$id': typeof ObrasIdRoute
  '/vendas/$id': typeof VendasIdRoute
  '/vendas/novo': typeof VendasNovoRoute
  '/vendas': typeof VendasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof ClientesRoute
  '/compras': typeof ComprasRoute
  '/contas': typeof ContasRoute
  '/financeiro': typeof FinanceiroRoute
  '/fornecedores': typeof FornecedoresRoute
  '/funcionarios': typeof FuncionariosRoute
  '/importacao': typeof ImportacaoRoute
  '/logistica': typeof LogisticaRoute
  '/notas-compra': typeof NotasCompraRoute
  '/ordens': typeof OrdensRoute
  '/ordens-compra': typeof OrdensCompraRoute
  '/produtos': typeof ProdutosRoute
  '/relatorio-contas': typeof RelatorioContasRoute
  '/estoque/entradas': typeof EstoqueEntradasRoute
  '/obras/$id': typeof ObrasIdRoute
  '/vendas/$id': typeof VendasIdRoute
  '/vendas/novo': typeof VendasNovoRoute
  '/vendas/': typeof VendasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/clientes'
    | '/compras'
    | '/contas'
    | '/financeiro'
    | '/fornecedores'
    | '/funcionarios'
    | '/importacao'
    | '/logistica'
    | '/notas-compra'
    | '/ordens'
    | '/ordens-compra'
    | '/produtos'
    | '/relatorio-contas'
    | '/estoque/entradas'
    | '/obras/$id'
    | '/vendas/$id'
    | '/vendas/novo'
    | '/vendas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/clientes'
    | '/compras'
    | '/contas'
    | '/financeiro'
    | '/fornecedores'
    | '/funcionarios'
    | '/importacao'
    | '/logistica'
    | '/notas-compra'
    | '/ordens'
    | '/ordens-compra'
    | '/produtos'
    | '/relatorio-contas'
    | '/estoque/entradas'
    | '/obras/$id'
    | '/vendas/$id'
    | '/vendas/novo'
    | '/vendas'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/clientes'
    | '/compras'
    | '/contas'
    | '/financeiro'
    | '/fornecedores'
    | '/funcionarios'
    | '/importacao'
    | '/logistica'
    | '/notas-compra'
    | '/ordens'
    | '/ordens-compra'
    | '/produtos'
    | '/relatorio-contas'
    | '/estoque/entradas'
    | '/obras/$id'
    | '/vendas/$id'
    | '/vendas/novo'
    | '/vendas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ClientesRoute: typeof ClientesRoute
  ComprasRoute: typeof ComprasRoute
  ContasRoute: typeof ContasRoute
  FinanceiroRoute: typeof FinanceiroRoute
  FornecedoresRoute: typeof FornecedoresRoute
  FuncionariosRoute: typeof FuncionariosRoute
  ImportacaoRoute: typeof ImportacaoRoute
  LogisticaRoute: typeof LogisticaRoute
  NotasCompraRoute: typeof NotasCompraRoute
  OrdensRoute: typeof OrdensRoute
  OrdensCompraRoute: typeof OrdensCompraRoute
  ProdutosRoute: typeof ProdutosRoute
  RelatorioContasRoute: typeof RelatorioContasRoute
  EstoqueEntradasRoute: typeof EstoqueEntradasRoute
  ObrasIdRoute: typeof ObrasIdRoute
  VendasIdRoute: typeof VendasIdRoute
  VendasNovoRoute: typeof VendasNovoRoute
  VendasIndexRoute: typeof VendasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relatorio-contas': {
      id: '/relatorio-contas'
      path: '/relatorio-contas'
      fullPath: '/relatorio-contas'
      preLoaderRoute: typeof RelatorioContasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordens-compra': {
      id: '/ordens-compra'
      path: '/ordens-compra'
      fullPath: '/ordens-compra'
      preLoaderRoute: typeof OrdensCompraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordens': {
      id: '/ordens'
      path: '/ordens'
      fullPath: '/ordens'
      preLoaderRoute: typeof OrdensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notas-compra': {
      id: '/notas-compra'
      path: '/notas-compra'
      fullPath: '/notas-compra'
      preLoaderRoute: typeof NotasCompraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistica': {
      id: '/logistica'
      path: '/logistica'
      fullPath: '/logistica'
      preLoaderRoute: typeof LogisticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importacao': {
      id: '/importacao'
      path: '/importacao'
      fullPath: '/importacao'
      preLoaderRoute: typeof ImportacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funcionarios': {
      id: '/funcionarios'
      path: '/funcionarios'
      fullPath: '/funcionarios'
      preLoaderRoute: typeof FuncionariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedores': {
      id: '/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof FornecedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contas': {
      id: '/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof ContasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras': {
      id: '/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof ComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas/': {
      id: '/vendas/'
      path: '/vendas'
      fullPath: '/vendas/'
      preLoaderRoute: typeof VendasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas/novo': {
      id: '/vendas/novo'
      path: '/vendas/novo'
      fullPath: '/vendas/novo'
      preLoaderRoute: typeof VendasNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas/$id': {
      id: '/vendas/$id'
      path: '/vendas/$id'
      fullPath: '/vendas/$id'
      preLoaderRoute: typeof VendasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obras/$id': {
      id: '/obras/$id'
      path: '/obras/$id'
      fullPath: '/obras/$id'
      preLoaderRoute: typeof ObrasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque/entradas': {
      id: '/estoque/entradas'
      path: '/estoque/entradas'
      fullPath: '/estoque/entradas'
      preLoaderRoute: typeof EstoqueEntradasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ClientesRoute: ClientesRoute,
  ComprasRoute: ComprasRoute,
  ContasRoute: ContasRoute,
  FinanceiroRoute: FinanceiroRoute,
  FornecedoresRoute: FornecedoresRoute,
  FuncionariosRoute: FuncionariosRoute,
  ImportacaoRoute: ImportacaoRoute,
  LogisticaRoute: LogisticaRoute,
  NotasCompraRoute: NotasCompraRoute,
  OrdensRoute: OrdensRoute,
  OrdensCompraRoute: OrdensCompraRoute,
  ProdutosRoute: ProdutosRoute,
  RelatorioContasRoute: RelatorioContasRoute,
  EstoqueEntradasRoute: EstoqueEntradasRoute,
  ObrasIdRoute: ObrasIdRoute,
  VendasIdRoute: VendasIdRoute,
  VendasNovoRoute: VendasNovoRoute,
  VendasIndexRoute: VendasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
